[package]
name = "fayez720-hue/perf-app"
version = "2.0.3"
description = "Next.js 15 Full Bundle - V20 Eval Isolation"

[dependencies]
"wasmer/winterjs" = "1.2.0"

[fs]
"/" = "."

[[module]]
name = "worker"
source = "index.mjs"
abi = "none"

[[command]]
name = "server"
module = "worker"
runner = "wasmer/winterjs"
args = ["index.mjs"]

[env]
NEXTAUTH_URL = "https://perf-app.wasmer.app"
NODE_ENV = "production"
PORT = "8080"
