name = "performance-app"
pages_build_output_dir = ".open-next"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXTAUTH_URL = "https://performance-app-6yb.pages.dev"
NODE_ENV = "production"

[[kv_namespaces]]
binding = "NEXT_CACHE_KV"
id = "dd749b2f662143ff9b04adb5ea673f30"
